# Generated by Django 4.2.23 on 2025-08-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('birthday', 'Birthday Cakes'), ('wedding', 'Wedding Cakes'), ('treat', 'Treats'), ('vegan', 'Vegan Cakes'), ('all', 'All Cakes & Treats')], max_length=20)),
                ('image', models.ImageField(upload_to='cakes/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
